services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: automotora
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/automotora?schema=public
      PORT: 3000
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/node_modules/.prisma

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  pgdata:
